# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  # Ubuntu 14.04
  config.vm.define "ubuntu1404", primary: true do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network "private_network", ip: "192.168.33.10"
    node.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory for mysql-server-5.6 on the VM.
      vb.memory = "1024"
    end
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup.yml"
      ansible.sudo = true
      #ansible.verbose = "vvv"
    end
  end

  # Debian 8
  config.vm.define "debian8" do |node|
    node.vm.box = "debian/jessie64"
    node.vm.network "private_network", ip: "192.168.33.11"
    node.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory for mysql-server-5.6 on the VM.
      vb.memory = "1024"
    end
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup.yml"
      ansible.sudo = true
    end
  end
  
end
#
# vi: set ft=ruby :
